Fix tox deps run (#291)
* tox.ini: Set skipsdist

On my debian bullseye system, tox is complaining:
ERROR: No pyproject.toml or setup.py file found. The expected locations are:
...

Set skipsdist to True to avoid that.

Signed-off-by: Arnaud Patard <apatard@hupstream.com>

* tox.ini: Avoid pip >= 22.1.1

Currently, things are failing due to pip-tools not working with pip
>= 22.1.1. So avoid these versions until https://github.com/jazzband/pip-tools/pull/1624
is merged and found in released version.

Signed-off-by: Arnaud Patard <apatard@hupstream.com>

* negative_test/roles/meta_invalid_role_namespace/meta/main.yml.md: update

Update file with version generated out of tox run.

Signed-off-by: Arnaud Patard <apatard@hupstream.com>

* Update tox.ini

Co-authored-by: Sorin Sbarnea <sorin.sbarnea@gmail.com>